"""Added professsionalmodel to services as column

Revision ID: 40f413b6d3d4
Revises: 8b95b3ebb6c0
Create Date: 2024-11-26 14:31:42.821218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f413b6d3d4'
down_revision = '8b95b3ebb6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('professional')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
