"""added professional details

Revision ID: 466f420e4210
Revises: 40f413b6d3d4
Create Date: 2024-11-26 15:04:57.513561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466f420e4210'
down_revision = '40f413b6d3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional_email', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_service_professional', 'professionals', ['professional_email'], ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('fk_service_professional', type_='foreignkey')
        batch_op.drop_column('professional_email')

    # ### end Alembic commands ###
