"""Describe the changes here

Revision ID: 8b95b3ebb6c0
Revises: 
Create Date: 2024-11-26 13:34:38.620520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b95b3ebb6c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_column('rate')

    # ### end Alembic commands ###
